{
 "title": "Pi-Hole Per Client",
 "tags": [
  "pihole",
  "dns",
  "system"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"pihole_clients\")\n|> keyValues(keyColumns: [\"client\"])\n|> group()\n|> keep(columns: [\"_value\"])\n"
   }
  ]
 },
 "panels": [
  {
   "title": "DNS Queries in Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> sum()\n  "
    }
   ]
  },
  {
   "title": "Domains Blocked in Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"blocklisted\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Blocked %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "blocked = from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"blocklisted\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 1d, fn: sum)\n  \ntotal = from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 1d, fn: sum)\n  \n  \njoin(tables: {t1: total, t2: blocked}, on: [\"_time\"])\n  |> map(fn: (r) => ({ \n     _value: (float(v: r._value_t2) / float(v: r._value_t1)) * 100.0\n  }))\n  |> last()"
    }
   ]
  },
  {
   "title": "Domains on Blocklist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// This relies on the pihole_stats measurement\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_stats\")\n  |> filter(fn: (r) => r._field == \"domains_being_blocked\")\n  |> last()"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "DNS Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "q/ps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Query Statuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field != \"total\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Blocked DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"blocklisted\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Blocked DNS Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "q/ps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pihole_clients\")\n  |> filter(fn: (r) => r._field == \"blocklisted\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}