{
 "title": "Octopus Pricing",
 "tags": [
  "Octopus",
  "electricity",
  "utilities"
 ],
 "time": { "from": "now-24h", "to": "now+24h" },
 "panels": [
  {
   "title": "Mean Import  Cost per kWh",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"cost_inc_vat\")/100 AS \"mean_cost_inc_vat\" FROM \"Systemstats\".\"autogen\".\"octopus_pricing\" WHERE $timeFilter AND \"charge_type\"='usage-charge' and tariff_direction != 'EXPORT' GROUP BY time(30m)"
    }
   ]
  },
  {
   "title": "Mean Export  Cost per kWh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"cost_inc_vat\")/100 AS \"mean_cost_inc_vat\" FROM \"Systemstats\".\"autogen\".\"octopus_pricing\" WHERE $timeFilter AND \"charge_type\"='usage-charge' and tariff_direction = 'EXPORT' GROUP BY time(30m)"
    }
   ]
  },
  {
   "title": "Total Import",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND \"is_export\" !='True' GROUP BY time(30m) FILL(null)"
    }
   ]
  },
  {
   "title": "Total Import",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND \"is_export\" ='True' GROUP BY time(30m) FILL(null)"
    }
   ]
  },
  {
   "title": "Cost per kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r._measurement == \"octopus_pricing\")\n |> filter(fn: (r) => r._field == \"cost_inc_vat\")\n |> filter(fn: (r) => r.tariff_direction != \"EXPORT\")\n |> aggregateWindow(every: 30m, fn: mean)"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND \"is_export\" !='True' GROUP BY time(30m) FILL(null)"
    }
   ]
  },
  {
   "title": "Consumption Cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND \"is_export\" !='True' GROUP BY time(30m) "
    },
    {
     "query": "SELECT mean(\"cost_inc_vat\")/100 AS \"mean_cost_inc_vat\" FROM \"Systemstats\".\"autogen\".\"octopus_pricing\" WHERE $timeFilter AND \"charge_type\"='usage-charge' and tariff_direction != 'EXPORT' GROUP BY time(30m) "
    }
   ]
  },
  {
   "title": "Export Price per kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r._measurement == \"octopus_pricing\")\n |> filter(fn: (r) => r._field == \"cost_inc_vat\")\n |> filter(fn: (r) => r.tariff_direction == \"EXPORT\")\n |> aggregateWindow(every: 30m, fn: mean)"
    }
   ]
  },
  {
   "title": "Export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND is_export=\"True\" GROUP BY time(30m) FILL(null)"
    }
   ]
  },
  {
   "title": "Export Price per kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "SELECT mean(\"cost_inc_vat\")/100 AS \"mean_cost_inc_vat\" FROM \"Systemstats\".\"autogen\".\"octopus_pricing\" WHERE $timeFilter AND \"charge_type\"='usage-charge' and tariff_direction = 'EXPORT' GROUP BY time(30m)"
    },
    {
     "query": "SELECT mean(\"consumption\") AS \"mean_consumption\" FROM \"Systemstats\".\"autogen\".\"octopus_consumption\" WHERE $timeFilter AND is_export =\"True\" GROUP BY time(30m) "
    }
   ]
  }
 ]
}