{
 "title": "Tor",
 "tags": [
  "tor",
  "anonymous overlay",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"tor\")\n|> keyValues(keyColumns: [\"host\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dormant Daemons",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\" and r._field == \"dormant\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max)"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"stats_fetch_failures\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  },
  {
   "title": "Network Liveness ($host)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_rx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> last()\n  |> map(fn: (r) => ({ \n     host: r.host,\n     _value: if r.network_liveness == \"up\" \n             then\n                2\n             else\n                0    \n  \t ,\n     _field: \"network_liveness\"\n  }))"
    }
   ]
  },
  {
   "title": "Software Version Status ($host)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_rx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> last()\n  |> map(fn: (r) => ({ \n     host: r.host,\n     _value: \n             if r.version_status == \"recommended\"\n             then\n                // Good to go\n                4\n             else if r.version_status == \"new\"\n             then\n               // Also Good\n               5\n            else if r.version_status == \"new in series\"\n            then\n               6\n\n             else if r.version_status == \"old\"\n             then\n                // might be an issue in future\n                3\n             else if r.version_status == \"unrecommended\"\n             then\n                // Uhoh\n                1\n            else if r.version_status == \"obsolete\"\n            then\n               2\n             else\n                // Unknown\n                7\n      ,\n     _field: \"version_status\"\n  }))"
    }
   ]
  },
  {
   "title": "Hibernation State ($host)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"accounting_bytes_read\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> last()\n|> map(fn: (r) => ({\n  \t_value: if r.accounting_hibernating_state == \"awake\" then\n        2\n     else if r.accounting_hibernating_state == \"soft\" then \n        4\n     else if r.accounting_hibernating_state == \"hard\" then \n        6\n     else \n     \t0\n  }))  "
    }
   ]
  },
  {
   "title": "Uploaded ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_tx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group()\n  |> difference()\n  |> filter(fn: (r) => r._value > 0)\n  |> sum()\n  |> map(fn: (r) => ({ r with\n  \t_value: r._value\n  }))"
    }
   ]
  },
  {
   "title": "Downloaded ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_rx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group()\n  |> difference()\n  |> filter(fn: (r) => r._value > 0)\n  |> sum()\n  |> map(fn: (r) => ({ r with\n  \t_value: r._value\n  }))"
    }
   ]
  },
  {
   "title": "Current Uptime ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\", \"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n  |> map(fn: (r) => ({ r with \n      _value: float(v: r._value) \n  }))"
    }
   ]
  },
  {
   "title": "Max Observed Upload ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_tx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\", \"_field\"])\n  |> sort(columns: [\"_time\"])  \n  |> derivative(unit: 1s, nonNegative: true)\n  |> max()\n  |> map(fn: (r) => ({ r with \n      _value: (r._value * 8.00)  \n  }))"
    }
   ]
  },
  {
   "title": "Max Observed Download ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_rx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\", \"_field\"])\n  |> sort(columns: [\"_time\"])  \n  |> derivative(unit: 1s, nonNegative: true)\n  |> max()\n  |> map(fn: (r) => ({ r with \n      _value: (r._value * 8.00)  \n  }))"
    }
   ]
  },
  {
   "title": "Max Observed Uptime ($host)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\", \"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> max()\n  |> map(fn: (r) => ({ r with \n      _value: float(v: r._value) \n  }))"
    }
   ]
  },
  {
   "title": "Guard Statuses ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"guards_down\" or\n            r._field == \"guards_never_connected\" or\n            r._field == \"guards_total\" or\n            r._field == \"guards_unlisted\" or\n            r._field == \"guards_unusable\" or\n            r._field == \"guards_up\")\n  |>aggregateWindow(every: v.windowPeriod, fn: max)\n  |>keep(columns: [\"_time\",\"host\", \"_field\", \"_value\"])\n            "
    }
   ]
  },
  {
   "title": "Daemon Uptime ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> map(fn: (r) => ({ \n         _time: r._time,\n         host: r.host,\n         _value: float(v: r._value)\n  }))"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"cpu\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"usage_system\" or\n          r._field == \"usage_user\" or\n          r._field == \"usage_iowait\"\n          )\n  |> filter(fn: (r) => r.cpu == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "CPU Usage ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"mem\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => \n          r._field == \"used_percent\"\n          )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  "
    }
   ]
  },
  {
   "title": "Network Throughput ($host)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"bytes_rx\" or r._field == \"bytes_tx\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\", \"_field\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with \n      _time: r._time,\n      _field: r._field,\n      host: r.host,\n      _value: r._value * 8.00\n  }))    \n"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Time Elapsed in Accounting Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"accounting_period_seconds_elapsed\")\n  |> last()\n  |> map(fn: (r) => ({\n  \t_value: float(v: r._value)\n  }))"
    }
   ]
  },
  {
   "title": "Time Remaining in Accounting Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"accounting_period_seconds_remaining\")\n  |> last()\n  |> map(fn: (r) => ({\n  \t_value: float(v: r._value)\n  }))"
    }
   ]
  },
  {
   "title": "Accounting Bytes Usage ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"accounting_bytes_read\" or r._field == \"accounting_bytes_write\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\",\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  "
    }
   ]
  },
  {
   "title": "Accounting Bytes Remaining ($host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"tor\")\n  |> filter(fn: (r) => r._field == \"accounting_bytes_remaining_read\" or r._field == \"accounting_bytes_remaining_write\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> group(columns: [\"host\",\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  "
    }
   ]
  }
 ]
}