{
 "title": "HaveIBeenPwned",
 "tags": [ "hibp" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "query": "SELECT DISTINCT search_domain FROM (select count, search_domain FROM \"hibp_domain_search\" WHERE $timeFilter GROUP BY domain)"
   },
   {
    "name": "breached_mail",
    "query": "SELECT DISTINCT email FROM (select count,email FROM \"hibp_domain_search\" WHERE $timeFilter AND search_domain='${domain}' GROUP BY email)"
   }
  ]
 },
 "panels": [
  { "title": "Domain ($domain)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Times $domain Exposed",
   "type": "timeseries",
   "description": "The total number of times that $domain has appeared in breaches.\n\nThis is a sum of all exposures, so if 2 users were in 1 breach, it counts as 2 not 1",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT sum(count) AS impacted FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='email' AND search_domain='${domain}' GROUP BY time($__interval) FILL(previous)"
    }
   ]
  },
  {
   "title": "Number of Breaches referencing $domain",
   "type": "timeseries",
   "description": "The number of documented breaches which involved mailboxes under $domain",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "SELECT count(DISTINCT service)  FROM (SELECT max(count) FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='pwned_site' AND search_domain='${domain}' GROUP BY time($__interval), service FILL(null)) GROUP BY time($__interval) FILL(previous)"
    }
   ]
  },
  {
   "title": "Number of Impacted Mailboxes (domain $domain)",
   "type": "timeseries",
   "description": "The number of distinct mailboxes under $domain which have appeared in breaches",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT max(count) AS mailboxes FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='search_domain' AND search_domain='${domain}' GROUP BY time($__interval) FILL(null)"
    }
   ]
  },
  {
   "title": "Breaches Per Mailbox (domain $domain)",
   "type": "timeseries",
   "description": "The number of documented inclusions per mailbox",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "SELECT max(count) AS breaches FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='email' AND search_domain='${domain}' GROUP BY time($__interval), email FILL(null)"
    }
   ]
  },
  {
   "title": "Breaches Relevant to $domain",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT last(emails) AS impacted FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='pwned_site' AND search_domain='${domain}' GROUP BY service"
    }
   ]
  },
  {
   "title": "Email ($breached_mail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Times $breached_mail Exposed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "query": "SELECT sum(count) AS impacted FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='email' AND search_domain='${domain}' and email='${breached_mail}' GROUP BY time($__interval) FILL(null)"
      }
     ]
    },
    {
     "title": "Breaches including $breached_mail",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "query": "SELECT last(emails) AS impacted FROM \"hibp_domain_search\" WHERE $timeFilter AND \"by\"='pwned_site' AND search_domain='${domain}' and emails =~ /$breached_mail/ GROUP BY service"
      }
     ]
    }
   ]
  }
 ]
}