{
 "title": "Tor Snowflake",
 "tags": [
  "tor",
  "system",
  "anonymous overlay",
  "relay",
  "snowflake"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"snowflake\")\n|> keyValues(keyColumns: [\"host\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections Handled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snowflake\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"conns\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Traffic Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snowflake\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"sent\")\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Traffic Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snowflake\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"recv\")\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snowflake\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"conns\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> drop(columns: [\"timeperiod_s\"])"
    }
   ]
  },
  {
   "title": "Traffic Relayed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snowflake\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"sent\" or r._field == \"recv\")\n  |> drop(columns: [\"timeperiod_s\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n\n  "
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_cpu\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"snowflake-proxy\")\n  |> filter(fn: (r) => r._field == \"usage_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])"
    }
   ]
  },
  {
   "title": "Container RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_mem\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"snowflake-proxy\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])\n\n"
    }
   ]
  }
 ]
}